#Numpy command practice sheet

#importing the numpy library as np 

In [10]:
import numpy as np

#Creating a numpy array

In [11]:
npArray1 = np.array([1,2,3,4,5,6,7,8,9,10])
npArray1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#Checking the type of the array

In [12]:
type(npArray1)

numpy.ndarray

#Creating a 2d array or matrix

In [13]:
npMatrix1 = np.array(([1,2,3,4,5],[6,7,8,9,10]))
npMatrix1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#Checking dimension and type of elements

In [14]:
npMatrix1.shape

(2, 5)

In [15]:
npMatrix1.dtype

dtype('int32')

#Targeting a element and changing its values

In [16]:
npMatrix1[0,0] = 0
npMatrix1

array([[ 0,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#Arranging values in ascending order

In [20]:
npMatrix2 = np.arange(0,10,1)
npMatrix2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Creating a array with 20 elements with element ranging from 0 to 10

In [21]:
npMatrix3 = np.linspace(0,10,20)
npMatrix3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [22]:
npMatrix3.shape

(20,)

#Creating a array with random values

In [24]:
npMatrix4 = np.random.rand(1,10)
npMatrix4

array([[0.22942442, 0.06142637, 0.84761865, 0.41435425, 0.92750666,
        0.23014047, 0.25302674, 0.29922343, 0.03826739, 0.59146105]])